### login

POST http://localhost:8080/com-jarkial-api-login/security/login HTTP/1.1
content-type: application/json

{
    "username": "ALEMUS",
    "password": "20240301MYPWD"
}

### findById

GET http://localhost:8081/com-jarkial-api-users/catalogs/find/1 HTTP/1.1
token: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJiZDk3MDkzOC0zMmExLTRjOTMtOTQ1Yi01NTU0NjcyMGE3YTMiLCJkYXRhIjpbIlJPTEVfQURNSU5JU1RSQURPUl9DQVRBTE9HT1MiXSwic3ViIjoiQUxFTVVTIiwiaWF0IjoxNzA5MzUzNjgzLCJleHAiOjE3MDkzNTU0ODN9.Bc8HG857Y7EL199cOB8J8pXQmDJ9n0x0yHY62QnkkIuFblUBpYbJmbgp6FX8pjKxpBn4pK28UJVoXCxUqqzblw

### listByPadre

GET http://localhost:8081/com-jarkial-api-users/catalogs/search/?idPadre=3&ctgCatNombre=p HTTP/1.1
token: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJjNzliYTM2ZS0zNWU0LTQ5MTgtOTkyZi03YWM0YjMxNDJmMjkiLCJkYXRhIjpbIlJPTEVfQURNSU5JU1RSQURPUl9DQVRBTE9HT1MiXSwic3ViIjoiQUxFTVVTIiwiaWF0IjoxNzA5MzU1NTExLCJleHAiOjE3MDkzNTczMTF9.eGAWeTjZG24HaseLqFTrFT3d0DJoukz66DImqCjSbfwT2_g2qH8L3GXILFpKDz6DRSAoisC71ZjSesXP3TFJww

### modify

PUT http://localhost:8081/com-jarkial-api-users/catalogs/modify/6 HTTP/1.1
token: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJhNThmNjNmZC0xNjQ0LTRlODEtODAzZC1jMjgyYjljYTFhZmIiLCJkYXRhIjpbIlJPTEVfQURNSU5JU1RSQURPUl9DQVRBTE9HT1MiXSwic3ViIjoiQUxFTVVTIiwiaWF0IjoxNzA5MDYyMDg2LCJleHAiOjE3MDkwNjM4ODZ9.l8Zexet57nZXx103bf944pg-HvzVsr6amcIjfwqfjJ_m_Tz095zVgtH4MRyfE7KmZICkCxqNd97hjhUhAr55hA
content-type: application/json

{
    "ctgCatalogoId": 6,
    "ctgCatalogoActivo": "1",
    "ctgCatalogoDescripcion": null,
    "ctgCatalogoNombre": "ROLE_ADMINISTRADOR_CATALOGOS",
    "ctgCatalogoPadre": 3,
    "ctgCatalogoSujetoOperacion": "1",
    "ctgCatalogoHomologacion": null,
    "ctgCatalogoPrioridad": 1,
    "ctgCatalogoAuxiliar1": null
}

### create

POST http://localhost:8081/com-jarkial-api-users/catalogs/new/ HTTP/1.1
token: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJhNThmNjNmZC0xNjQ0LTRlODEtODAzZC1jMjgyYjljYTFhZmIiLCJkYXRhIjpbIlJPTEVfQURNSU5JU1RSQURPUl9DQVRBTE9HT1MiXSwic3ViIjoiQUxFTVVTIiwiaWF0IjoxNzA5MDYyMDg2LCJleHAiOjE3MDkwNjM4ODZ9.l8Zexet57nZXx103bf944pg-HvzVsr6amcIjfwqfjJ_m_Tz095zVgtH4MRyfE7KmZICkCxqNd97hjhUhAr55hA
content-type: application/json

{
    "ctgCatalogoId": 0,
    "ctgCatalogoActivo": "1",
    "ctgCatalogoDescripcion": null,
    "ctgCatalogoNombre": "ROLE_ADMINISTRADOR_USUARIOS",
    "ctgCatalogoPadre": 3,
    "ctgCatalogoSujetoOperacion": "1",
    "ctgCatalogoHomologacion": null,
    "ctgCatalogoPrioridad": 1,
    "ctgCatalogoAuxiliar1": null
}

### delete

DELETE http://localhost:8081/com-jarkial-api-users/catalogs/erase/?id=0 HTTP/1.1
token: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJhNThmNjNmZC0xNjQ0LTRlODEtODAzZC1jMjgyYjljYTFhZmIiLCJkYXRhIjpbIlJPTEVfQURNSU5JU1RSQURPUl9DQVRBTE9HT1MiXSwic3ViIjoiQUxFTVVTIiwiaWF0IjoxNzA5MDYyMDg2LCJleHAiOjE3MDkwNjM4ODZ9.l8Zexet57nZXx103bf944pg-HvzVsr6amcIjfwqfjJ_m_Tz095zVgtH4MRyfE7KmZICkCxqNd97hjhUhAr55hA

###